const MIN_PRICE = 500;
const MAX_PRICE = 20000;
const TRUE = 1;
const FALSE = 0;

const MIN_RATE = 0;
const MAX_RATE = 5;
const MIN_CONVENIENCES = 1;
const MAX_CONVENIENCES = 7;
const FIRST_WEEK_DAY = 1;
const LAST_WEEK_DAY = 7;
const MIN_ROOMS = 1;
const MAX_ROOMS = 8;
const MIN_GUEST = 1;
const MAX_GUEST = 10;
const MIN_COMMENT = 0;
const MAX_COMMENT = 1000;

export { MIN_PRICE, MAX_PRICE, TRUE, FALSE, MIN_RATE, MAX_RATE, MIN_CONVENIENCES, MAX_CONVENIENCES, FIRST_WEEK_DAY, LAST_WEEK_DAY, MIN_ROOMS, MAX_ROOMS, MIN_GUEST, MAX_GUEST, MIN_COMMENT, MAX_COMMENT };
